# Generated by Django 4.1.1 on 2022-12-02 10:01

from decimal import Decimal
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth0", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="FuelOilData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_oil_type",
                    models.CharField(
                        choices=[
                            ("HFO", "HFO"),
                            ("LSFO", "LSFO"),
                            ("MDO", "MDO"),
                            ("MGO", "MGO"),
                            ("LPGP", "LPG (Propane)"),
                            ("LPGB", "LPG (Butane"),
                            ("METH", "Methanol"),
                            ("ETH", "Ethanol"),
                            ("LNG", "LNG"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "total_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "receipt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "debunkering",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "rob",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("breakdown", models.JSONField()),
            ],
            options={
                "db_table": "fuel_oil_data",
            },
        ),
        migrations.CreateModel(
            name="LubricatingOilData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("fuel_oil_type", models.CharField(max_length=64)),
                (
                    "total_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "receipt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "debunkering",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "rob",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "lubricating_oil_data",
            },
        ),
        migrations.CreateModel(
            name="ReportHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("leg_num", models.PositiveSmallIntegerField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("NOON", "Noon at Sea"),
                            ("DSBY", "Noon Waiting"),
                            ("DCSP", "Noon in Port"),
                            ("ASBY", "Departure"),
                            ("AFWE", "Arrival"),
                            ("BDN", "Bunker Delivery Note"),
                            ("EVNT", "Event in Harbour"),
                        ],
                        max_length=4,
                    ),
                ),
                ("report_num", models.PositiveIntegerField()),
                ("report_date", models.DateTimeField()),
                ("report_tz", timezone_field.fields.TimeZoneField(use_pytz=False)),
                ("summer_time", models.BooleanField()),
                ("position", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
            ],
            options={
                "db_table": "report_headers",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("imo_reg", models.PositiveIntegerField()),
                (
                    "ship_type",
                    models.CharField(
                        choices=[
                            ("CNTR", "Container Ship"),
                            ("BULK", "Bulk Carrier"),
                            ("OIL", "Oil Tanker"),
                            ("GAS", "Gas/LNG Tanker"),
                            ("RORO", "Roll-On Roll-Off Ships"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
            ],
            options={
                "db_table": "ships",
            },
        ),
        migrations.CreateModel(
            name="ConsumptionConditionData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                (
                    "consumption_type",
                    models.CharField(
                        choices=[
                            ("NTON", "Noon to Noon"),
                            ("LTOS", "Last Report to Standby"),
                            ("INHP", "In Harbour / In Port"),
                            ("STOR", "Standby to Run Up"),
                            ("NTOS", "Noon to Standby"),
                            ("STOF", "Standby to FWE"),
                            ("LTOE", "Last Report to Event"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
            options={
                "db_table": "consumption_conduiion_data",
                "unique_together": {("report_header", "consumption_type")},
            },
        ),
        migrations.CreateModel(
            name="DistancePerformanceData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                (
                    "hours_since_noon",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("48")),
                        ],
                    ),
                ),
                (
                    "hours_total",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "distance_to_go",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("remarks_for_changes", models.TextField()),
                (
                    "distance_obs_since_noon",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "distance_obs_total",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "distance_eng_since_noon",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "distance_eng_total",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "revolution_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "speed_since_noon",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "rpm_since_noon",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "slip_since_noon",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "speed_avg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "rpm_avg",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "slip_avg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "distance_performance_data",
            },
        ),
        migrations.CreateModel(
            name="FuelOilDataCorrection",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("correction", models.DecimalField(decimal_places=2, max_digits=7)),
                ("remarks", models.TextField()),
                (
                    "fuel_oil_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.fueloildata",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_oil_data_corrections",
            },
        ),
        migrations.CreateModel(
            name="HeavyWeatherData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "observed_distance",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "fuel_consumption",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "wind_direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("NE", "Northeast"),
                            ("SE", "Southeast"),
                            ("SW", "Southwest"),
                            ("NW", "Northwest"),
                            ("NNE", "North-Northeast"),
                            ("ENE", "East-Northeast"),
                            ("ESE", "East-Southeast"),
                            ("SSE", "South-Southeast"),
                            ("SSW", "South-Southwest"),
                            ("WSW", "West-Southwest"),
                            ("WNW", "West-Northwest"),
                            ("NNW", "North-Northwest"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "sea_direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("NE", "Northeast"),
                            ("SE", "Southeast"),
                            ("SW", "Southwest"),
                            ("NW", "Northwest"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sea_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Calm (Glassy)"),
                            (1, "Calm (Rippled)"),
                            (2, "Smooth (Wavelets)"),
                            (3, "Slight"),
                            (4, "Moderate"),
                            (5, "Rough"),
                            (6, "Very Rough"),
                            (7, "High"),
                            (8, "Very High"),
                            (9, "Phenomal"),
                        ]
                    ),
                ),
                (
                    "max_wave_height",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("remarks", models.TextField()),
            ],
            options={
                "db_table": "heavy_weather_data",
            },
        ),
        migrations.CreateModel(
            name="LubricatingOilDataCorrection",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("correction", models.DecimalField(decimal_places=2, max_digits=7)),
                ("remarks", models.TextField()),
                (
                    "lubricating_oil_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.lubricatingoildata",
                    ),
                ),
            ],
            options={
                "db_table": "lubricating_oil_data_corrections",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                ("departure_port", models.CharField(max_length=6)),
                ("departure_date", models.DateTimeField()),
                ("arrival_port", models.CharField(max_length=6)),
                ("arrival_date", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoppageData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "reduced_rpm",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("position", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("reason", models.CharField(max_length=4)),
                ("remarks", models.TextField()),
            ],
            options={
                "db_table": "stoppage_data",
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                (
                    "weather_notation",
                    models.CharField(
                        choices=[
                            ("B", "Blue sky (Cloud 0-2)"),
                            ("BC", "Fine but Cloudy (Cloud 3-7)"),
                            ("C", "Cloudy (Cloud 8-10)"),
                            ("D", "Drizzling rain"),
                            ("F", "Fog"),
                            ("G", "Gloom"),
                            ("H", "Hail"),
                            ("L", "Lightning"),
                            ("M", "Mist"),
                            ("O", "Overcast (Cloud 10)"),
                            ("P", "Passing showers"),
                            ("Q", "Squalls"),
                            ("R", "Rain"),
                            ("S", "Snow"),
                            ("T", "Thunder"),
                            ("U", "Ugly threatening weather"),
                            ("W", "Dew"),
                            ("Z", "Haze"),
                        ],
                        max_length=2,
                    ),
                ),
                ("visibility", models.PositiveSmallIntegerField()),
                (
                    "wind_direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("NE", "Northeast"),
                            ("SE", "Southeast"),
                            ("SW", "Southwest"),
                            ("NW", "Northwest"),
                            ("NNE", "North-Northeast"),
                            ("ENE", "East-Northeast"),
                            ("ESE", "East-Southeast"),
                            ("SSE", "South-Southeast"),
                            ("SSW", "South-Southwest"),
                            ("WSW", "West-Southwest"),
                            ("WNW", "West-Northwest"),
                            ("NNW", "North-Northwest"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "sea_direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("NE", "Northeast"),
                            ("SE", "Southeast"),
                            ("SW", "Southwest"),
                            ("NW", "Northwest"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sea_state",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Calm (Glassy)"),
                            (1, "Calm (Rippled)"),
                            (2, "Smooth (Wavelets)"),
                            (3, "Slight"),
                            (4, "Moderate"),
                            (5, "Rough"),
                            (6, "Very Rough"),
                            (7, "High"),
                            (8, "Very High"),
                            (9, "Phenomal"),
                        ]
                    ),
                ),
                (
                    "swell_direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("E", "East"),
                            ("S", "South"),
                            ("W", "West"),
                            ("NE", "Northeast"),
                            ("SE", "Southeast"),
                            ("SW", "Southwest"),
                            ("NW", "Northwest"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "swell_scale",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "No Swell"),
                            (1, "Low Swell (Short or Average)"),
                            (2, "Low Swell (Long)"),
                            (3, "Moderate Swell (Short)"),
                            (4, "Moderate Swell (Average)"),
                            (5, "Moderate Swell (Long)"),
                            (6, "Heavy Swell (Short)"),
                            (7, "Heavy Swell (Moderate)"),
                            (8, "Heavy Swell (Long)"),
                            (9, "Confused Swell"),
                        ]
                    ),
                ),
                ("air_pressure", models.PositiveSmallIntegerField()),
                (
                    "air_temperature_dry",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "air_temperature_wet",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "sea_temperature",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "ice_condiction",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("LOW", "LOW"),
                            ("MOD", "MODERATE"),
                            ("HIGH", "HIGH"),
                            ("EXT", "EXTENSIVE"),
                        ],
                        default="NONE",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "db_table": "weather_data",
            },
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("voyage_num", models.PositiveIntegerField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marinanet.ship"
                    ),
                ),
            ],
            options={
                "db_table": "voyages",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marinanet.company",
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="ShipUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "privilege",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Read only access"), (1, "Read and Write access")]
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marinanet.ship"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ship_users",
            },
        ),
        migrations.AddField(
            model_name="ship",
            name="assigned_users",
            field=models.ManyToManyField(
                through="marinanet.ShipUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="marinanet.company"
            ),
        ),
        migrations.AddField(
            model_name="reportheader",
            name="voyage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="marinanet.voyage"
            ),
        ),
        migrations.CreateModel(
            name="FreshWaterData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ccdata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.consumptionconditiondata",
                    ),
                ),
                ("consumed", models.PositiveIntegerField()),
                ("evaporated", models.PositiveIntegerField()),
                ("received", models.PositiveIntegerField()),
                ("discharged", models.PositiveIntegerField()),
                ("rob", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "fresh_water_data",
            },
        ),
        migrations.AddField(
            model_name="lubricatingoildata",
            name="ccdata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="marinanet.consumptionconditiondata",
            ),
        ),
        migrations.AddField(
            model_name="fueloildata",
            name="ccdata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="marinanet.consumptionconditiondata",
            ),
        ),
    ]
