# Generated by Django 4.1.1 on 2022-09-19 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth0", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("imo_reg", models.PositiveIntegerField()),
                (
                    "ship_type",
                    models.CharField(
                        choices=[
                            ("CNTR", "Container Ship"),
                            ("BULK", "Bulk Carrier"),
                            ("OIL", "Oil Tanker"),
                            ("GAS", "Gas/LNG Tanker"),
                            ("RORO", "Roll-On Roll-Off Ships"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ships",
            },
        ),
        migrations.CreateModel(
            name="ShipUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privilege",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Read only access"), (1, "Read and Write access")]
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="marinanet.ship"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ship_users",
            },
        ),
        migrations.AddField(
            model_name="ship",
            name="assigned_users",
            field=models.ManyToManyField(
                through="marinanet.ShipUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="marinanet.company"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="marinanet.company",
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
