# Generated by Django 4.1.1 on 2022-12-21 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreshWaterTotalConsumptionData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ccdata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.totalconsumptiondata",
                    ),
                ),
                ("consumed", models.PositiveIntegerField()),
                ("evaporated", models.PositiveIntegerField()),
                ("received", models.PositiveIntegerField()),
                ("discharged", models.PositiveIntegerField()),
                ("rob", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "fresh_water_total_consumption_data",
            },
        ),
    ]
