# Generated by Django 4.1.1 on 2022-12-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherdata",
            old_name="ice_condiction",
            new_name="ice_condition",
        ),
        migrations.AlterUniqueTogether(
            name="voyage",
            unique_together={("ship", "voyage_num")},
        ),
    ]
