# Generated by Django 4.1.1 on 2022-12-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0002_rename_ice_condiction_weatherdata_ice_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=127)),
                ('deadweight_tonnage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cargo_unit', models.CharField(max_length=50)),
                ('fuel_options', models.JSONField()),
                ('lubricating_oil_options', models.JSONField()),
                ('machinery_options', models.JSONField()),
                ('propeller_pitch', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='marinanet.ship')),
            ],
        ),
    ]
