# Generated by Django 4.1.1 on 2022-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0002_freshwatertotalconsumptiondata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freshwatertotalconsumptiondata",
            old_name="ccdata",
            new_name="tcdata",
        ),
        migrations.RenameField(
            model_name="fueloiltotalconsumptiondata",
            old_name="tc_data",
            new_name="tcdata",
        ),
        migrations.RenameField(
            model_name="lubricatingoiltotalconsumptiondata",
            old_name="tc_data",
            new_name="tcdata",
        ),
    ]
