# Generated by Django 4.1.1 on 2022-10-21 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0002_reportheader_freshwaterdata_heavyweatherdata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        ),
        migrations.RemoveField(
            model_name="voyage",
            name="arrival_date",
        ),
        migrations.RemoveField(
            model_name="voyage",
            name="arrival_port",
        ),
        migrations.RemoveField(
            model_name="voyage",
            name="departure_date",
        ),
        migrations.RemoveField(
            model_name="voyage",
            name="departure_port",
        ),
        migrations.AddField(
            model_name="reportheader",
            name="report_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="ice_condiction",
            field=models.TextField(
                choices=[
                    ("NONE", "NONE"),
                    ("LOW", "LOW"),
                    ("MOD", "MODERATE"),
                    ("HIGH", "HIGH"),
                    ("EXT", "EXTENSIVE"),
                ],
                default="NONE",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="reportheader",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="shipuser",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="voyage",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Inactive"), (1, "Active")], default=1
            ),
        ),
    ]
