# Generated by Django 4.1.1 on 2023-01-12 07:10

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0002_alter_fueloildata_breakdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bdndata",
            name="delivered_oil_type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="bdndata",
            name="density_15",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="bdndata",
            name="specific_gravity_15",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="bdndata",
            name="viscosity_value",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="heavyweatherdata",
            name="observed_distance",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="heavyweatherdata",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="performancedata",
            name="slip_average",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="performancedata",
            name="slip_since_last",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="ship",
            name="imo_reg",
            field=models.PositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(1000000),
                    django.core.validators.MaxValueValidator(9999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shipspecs",
            name="fuel_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("HFO", "HFO"),
                        ("LSFO", "LSFO"),
                        ("MDO", "MDO"),
                        ("MGO", "MGO"),
                        ("LPGP", "LPG (Propane)"),
                        ("LPGB", "LPG (Butane"),
                        ("METH", "Methanol"),
                        ("ETH", "Ethanol"),
                        ("LNG", "LNG"),
                    ],
                    max_length=4,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="shipspecs",
            name="lubricating_oil_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="shipspecs",
            name="machinery_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
    ]
