# Generated by Django 4.1.1 on 2022-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0003_shipspecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipspecs',
            name='deadweight_tonnage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
