# Generated by Django 4.1.1 on 2022-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marinanet",
            "0003_rename_ccdata_freshwatertotalconsumptiondata_tcdata_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArrrivalFWETimeAndPosition",
            new_name="ArrivalFWETimeAndPosition",
        ),
        migrations.AlterField(
            model_name="distanceperformancedata",
            name="remarks_for_changes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plannedoperations",
            name="planned_operation_othersdetails",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portoperations",
            name="others_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
