# Generated by Django 4.1.1 on 2023-01-12 08:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0004_shipspecs_fuel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyagelegdata",
            name="cargo_total_at_departure",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="last_report_tz",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="time_standby_to_cosp",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="distancetimedata",
            name="remarks_for_changes",
            field=models.TextField(default="NIL"),
        ),
    ]
