# Generated by Django 4.1.1 on 2022-12-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0004_rename_arrrivalfwetimeandposition_arrivalfwetimeandposition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyageleg',
            old_name='depature_tz',
            new_name='departure_tz',
        ),
    ]
