# Generated by Django 4.1.1 on 2022-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0004_alter_shipspecs_deadweight_tonnage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipspecs',
            options={'verbose_name_plural': 'ship_specs'},
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('CNTR', 'Container Ship'), ('BULK', 'Bulk Carrier'), ('OIL', 'Oil Tanker'), ('GAS', 'Gas/LNG Tanker'), ('RORO', 'Roll-On Roll-Off Ships'), ('GEN', 'General Cargo Ship'), ('REFC', 'Refrigerated Cargo Carrier'), ('COMB', 'Combination Carrier'), ('LNGC', 'LNG Carrier'), ('RORV', 'Ro-Ro Cargo Ship (Vehicle Carrier)'), ('RORP', 'Ro-Ro Passenger Ship'), ('CRUZ', 'Cruise Passenger Ship')], max_length=4),
        ),
        migrations.AlterModelTable(
            name='shipspecs',
            table='ship_specs',
        ),
    ]
