# Generated by Django 4.1.1 on 2022-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0005_rename_depature_tz_voyageleg_departure_tz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freshwaterdata",
            old_name="evaporated",
            new_name="generated",
        ),
        migrations.RenameField(
            model_name="freshwatertotalconsumptiondata",
            old_name="evaporated",
            new_name="generated",
        ),
        migrations.AddField(
            model_name="heavyweatherdata",
            name="weather_notation",
            field=models.CharField(
                choices=[
                    ("B", "Blue sky (Cloud 0-2)"),
                    ("BC", "Fine but Cloudy (Cloud 3-7)"),
                    ("C", "Cloudy (Cloud 8-10)"),
                    ("D", "Drizzling rain"),
                    ("F", "Fog"),
                    ("G", "Gloom"),
                    ("H", "Hail"),
                    ("L", "Lightning"),
                    ("M", "Mist"),
                    ("O", "Overcast (Cloud 10)"),
                    ("P", "Passing showers"),
                    ("Q", "Squalls"),
                    ("R", "Rain"),
                    ("S", "Snow"),
                    ("T", "Thunder"),
                    ("U", "Ugly threatening weather"),
                    ("W", "Dew"),
                    ("Z", "Haze"),
                ],
                default="B",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
