# Generated by Django 4.1.1 on 2022-12-12 08:34

import django.contrib.postgres.fields
from django.db import migrations, models
import marinanet.models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0005_alter_shipspecs_options_alter_ship_ship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='allowed_report_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=marinanet.models.get_default_allowed_report_types, size=None),
        ),
        migrations.AlterField(
            model_name='reportheader',
            name='report_type',
            field=models.CharField(choices=[('NOON', 'Noon at Sea'), ('DSBY', 'Departure: Standby'), ('DCSP', 'Departure: COSP'), ('ASBY', 'Arrival: Standby'), ('AFWE', 'Arrival: FWE'), ('BDN', 'Bunker Delivery Note'), ('EVNT', 'Event in Harbour')], max_length=4),
        ),
    ]
