# Generated by Django 4.1.1 on 2023-01-12 13:15

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0005_voyagelegdata_cargo_total_at_departure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyagelegdata",
            name="last_operation",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="distancetimedata",
            name="remarks_for_changes",
            field=models.TextField(),
        ),
    ]
