# Generated by Django 4.1.1 on 2022-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0006_rename_evaporated_freshwaterdata_generated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportheader",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("NOON", "Noon at Sea"),
                    ("DSBY", "Departure: Standby"),
                    ("DCSP", "Departure: COSP"),
                    ("ASBY", "Arrival: Standby"),
                    ("AFWE", "Arrival: FWE"),
                    ("BDN", "Bunker Delivery Note"),
                    ("EVHB", "Event in Harbour"),
                    ("EVPO", "Event in Port"),
                    ("NNHB", "Noon in Harbour"),
                    ("NNPO", "Noon in Port"),
                ],
                max_length=4,
            ),
        ),
    ]
