# Generated by Django 4.1.1 on 2023-01-13 09:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0007_alter_cargooperation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyagelegdata",
            name="revolution_count_standby_to_cosp",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="time_stopped_at_sea",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
