# Generated by Django 4.1.1 on 2022-12-29 13:56

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0007_alter_reportheader_report_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDNData",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="marinanet.reportheader",
                    ),
                ),
                ("bunkering_port", models.CharField(max_length=6)),
                ("bunkering_date", models.DateTimeField()),
                (
                    "bdn_file",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1500), size=None
                    ),
                ),
                (
                    "delivered_oil_type",
                    models.CharField(
                        choices=[
                            ("HFO", "HFO"),
                            ("LSFO", "LSFO"),
                            ("MDO", "MDO"),
                            ("MGO", "MGO"),
                            ("LPGP", "LPG (Propane)"),
                            ("LPGB", "LPG (Butane"),
                            ("METH", "Methanol"),
                            ("ETH", "Ethanol"),
                            ("LNG", "LNG"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "delivered_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "density_15",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "specific_gravity_15",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "viscosity_value",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "viscosity_temperature",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "flash_point",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "sulfur_content",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                ("sample_sealing_marpol", models.CharField(max_length=64)),
                ("sample_sealing_ship", models.CharField(max_length=64)),
                ("sample_sealing_barge", models.CharField(max_length=64)),
                ("alongside_date", models.DateTimeField()),
                ("hose_connection_date", models.DateTimeField()),
                ("pump_start_date", models.DateTimeField()),
                ("pump_stop_date", models.DateTimeField()),
                ("hose_disconnection_date", models.DateTimeField()),
                ("slipoff_date", models.DateTimeField()),
                ("purchaser", models.CharField(max_length=128)),
                ("barge_name", models.CharField(max_length=128)),
                ("supplier_name", models.CharField(max_length=128)),
                ("supplier_address", models.TextField()),
                (
                    "supplier_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
