# Generated by Django 4.1.1 on 2023-01-14 07:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0008_voyagelegdata_revolution_count_standby_to_cosp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualperformancedata',
            name='sailing_time',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
