# Generated by Django 4.1.1 on 2023-01-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0009_voyagelegdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voyagelegdata",
            name="freshwater_data",
        ),
        migrations.RemoveField(
            model_name="voyagelegdata",
            name="fuel_oil_data",
        ),
        migrations.RemoveField(
            model_name="voyagelegdata",
            name="lube_oil_data",
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="freshwater_rob",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_cons_in_harbour_port",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_cons_pilot_to_pilot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_cons_port_to_port",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_robs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="lube_oil_robs",
            field=models.JSONField(default=dict),
        ),
    ]
