# Generated by Django 4.1.1 on 2023-01-14 08:45

from decimal import Decimal
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0009_remove_bdndata_specific_gravity_15"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voyagelegdata",
            old_name="distance_standby_to_cosp",
            new_name="distance_obs_standby_to_cosp",
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="freshwater_cons_in_harbour_port",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="freshwater_discharge_in_harbour_port",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="freshwater_gen_in_harbour_port",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="freshwater_receipt_in_harbour_port",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_discharge_in_harbour_port",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="fuel_oil_receipt_in_harbour_port",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="lube_oil_cons_in_harbour_port",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="lube_oil_discharge_in_harbour_port",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="voyagelegdata",
            name="lube_oil_receipt_in_harbour_port",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="actualperformancedata",
            name="sailing_time",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
