# Generated by Django 4.1.1 on 2023-01-14 08:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marinanet",
            "0010_rename_distance_standby_to_cosp_voyagelegdata_distance_obs_standby_to_cosp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voyagelegdata",
            name="distance_eng_standby_to_cosp",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
