# Generated by Django 4.1.1 on 2023-01-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0010_remove_voyagelegdata_freshwater_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyagelegdata",
            name="freshwater_rob",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
