# Generated by Django 4.1.1 on 2023-01-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0011_alter_voyagelegdata_freshwater_rob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voyagelegdata",
            old_name="plannedoperations",
            new_name="planned_operations",
        ),
    ]
