# Generated by Django 4.1.1 on 2023-01-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0009_alter_actualperformancedata_sailing_time'),
        ('marinanet', '0012_rename_fuel_oil_discharge_in_harbour_port_voyagelegdata_fuel_oil_debunker_in_harbour_port_and_more'),
    ]

    operations = [
    ]
