# Generated by Django 4.1.1 on 2023-01-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0013_merge_20230114_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdndata',
            name='is_before_arrival',
            field=models.BooleanField(null=True),
        ),
    ]
