# Generated by Django 4.1.1 on 2023-01-15 05:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0015_alter_voyagelegdata_freshwater_cons_in_harbour_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdndata',
            name='bdn_file',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=3000), size=None),
        ),
    ]
