# Generated by Django 4.1.1 on 2023-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0016_alter_bdndata_bdn_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyagelegdata",
            name="propeller_pitch",
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
