# Generated by Django 4.1.1 on 2023-01-15 12:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marinanet", "0017_alter_voyagelegdata_propeller_pitch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyagelegdata",
            name="time_standby_to_cosp",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
    ]
