# Generated by Django 4.1.1 on 2023-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marinanet', '0018_alter_voyagelegdata_time_standby_to_cosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedoperations',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
