# Generated by Django 4.1.1 on 2023-02-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vesselreporting", "0002_alter_reportedge_next_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyagelegprogress",
            name="voyage_leg",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="vesselreporting.voyageleg",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voyageleg",
            unique_together={("voyage", "leg_num")},
        ),
        migrations.AddConstraint(
            model_name="reportedge",
            constraint=models.UniqueConstraint(
                fields=("previous_report", "next_report"),
                name="report_edge_reports_unique",
            ),
        ),
    ]
