# Generated by Django 4.1.1 on 2023-02-27 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("vesselreporting", "0003_alter_voyagelegprogress_voyage_leg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalRemarks",
            fields=[
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "report_header",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="vesselreporting.reportheader",
                    ),
                ),
                ("remarks", models.TextField()),
            ],
            options={
                "db_table": "report_additional_remarks",
            },
        ),
    ]
