# Generated by Django 4.1.1 on 2023-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carboncalc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyefficiencytechnicalfile",
            name="energy_efficiency_index_type",
            field=models.CharField(
                choices=[("EEXI", "EEXI"), ("EEDI", "EEDI")],
                default="EEXI",
                max_length=4,
            ),
        ),
    ]
