# Generated by Django 4.1.1 on 2023-02-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carboncalc", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetcii",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="standardizeddatareportingfile",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="standardizeddatareportingdata",
            name="reporting_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="carboncalc.standardizeddatareportingfile",
            ),
        ),
        migrations.AddField(
            model_name="standardizeddatareportingdata",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="energyefficiencytechnicalfile",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="ciishipyearboundaries",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="ciirawdata",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="ciiconfig",
            name="ship",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddField(
            model_name="calculatedcii",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.ship"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetcii",
            constraint=models.UniqueConstraint(
                fields=("ship", "year"), name="targetcii_ship_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="standardizeddatareportingfile",
            constraint=models.UniqueConstraint(
                fields=("ship", "year"), name="standardizeddatareportingfile_ship_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="ciishipyearboundaries",
            constraint=models.UniqueConstraint(
                fields=("ship", "year"), name="ciishipyearboundaries_ship_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="ciirawdata",
            constraint=models.UniqueConstraint(
                fields=("ship", "year"), name="ciirawdata_ship_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="ciiconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("eu_mrv_method__isnull", False), ("eu_mrv", False), _connector="OR"
                ),
                name="eu_mrv_details_null_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ciiconfig",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("engine_power_limit_type__isnull", False),
                        ("engine_power_limit_value__isnull", False),
                    ),
                    ("is_engine_power_limited", False),
                    _connector="OR",
                ),
                name="engine_power_limit_details_null_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="calculatedcii",
            constraint=models.UniqueConstraint(
                fields=("ship", "year"), name="calculatedcii_ship_year"
            ),
        ),
    ]
