# Generated by Django 4.1.1 on 2023-02-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carboncalc", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ciiconfig",
            name="eu_mrv_details_null_check",
        ),
        migrations.RemoveConstraint(
            model_name="ciiconfig",
            name="engine_power_limit_details_null_check",
        ),
    ]
