# Generated by Django 4.1.1 on 2023-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carboncalc", "0003_remove_ciiconfig_eu_mrv_details_null_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciiconfig",
            name="engine_power_limit_type",
            field=models.CharField(
                choices=[("EPL", "EPL"), ("SPL", "Shapoli")], max_length=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ciiconfig",
            name="eu_mrv_method",
            field=models.CharField(
                choices=[
                    ("MRVA", "MRV Method A"),
                    ("MRVB", "MRV Method B"),
                    ("MRVC", "MRV Method C"),
                    ("MRVD", "MRV Method D"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
