# Generated by Django 4.1.1 on 2023-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carboncalc", "0004_alter_ciiconfig_engine_power_limit_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ciiconfig",
            name="applcable_cii",
        ),
        migrations.AddField(
            model_name="ciiconfig",
            name="applicable_cii",
            field=models.CharField(
                choices=[("AER", "AER"), ("CGDIST", "cgDIST")],
                default="AER",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ciiconfig",
            name="engine_power_limit_type",
            field=models.CharField(
                blank=True,
                choices=[("EPL", "EPL"), ("SPL", "Shapoli")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ciiconfig",
            name="engine_power_limit_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ciiconfig",
            name="eu_mrv_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MRVA", "MRV Method A"),
                    ("MRVB", "MRV Method B"),
                    ("MRVC", "MRV Method C"),
                    ("MRVD", "MRV Method D"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
