# Generated by Django 4.1.1 on 2023-02-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carboncalc", "0005_remove_ciiconfig_applcable_cii_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardizeddatareportingdata",
            name="reporting_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="carboncalc.standardizeddatareportingfile",
            ),
        ),
        migrations.AlterField(
            model_name="standardizeddatareportingfile",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
