# Generated by Django 4.1.1 on 2023-03-01 18:24

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DCSVoyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("voyage_num", models.CharField(max_length=7)),
                ("departure_port", models.CharField(max_length=7)),
                ("departure_date", models.DateTimeField()),
                ("departure_cargo_operation", models.BooleanField()),
                ("arrival_port", models.CharField(max_length=7)),
                ("arrival_date", models.DateTimeField()),
                ("time_at_sea", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "distance_travelled",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "time_idle_at_anchorage",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "cargo_carried_passenger",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "cargo_carried_weight_volume",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "transport_work_passenger",
                    models.DecimalField(decimal_places=3, max_digits=13),
                ),
                (
                    "transport_work_weight_volume",
                    models.DecimalField(decimal_places=3, max_digits=13),
                ),
                (
                    "rob_at_departure",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "rob_at_arrival",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "at_berth_consumption",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "net_consumption",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "bunkering_before_arrival",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "bunkering_after_arrival",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "debunkering_before_arrival",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "debunkering_after_arrival",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "correction_time_at_sea",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "correction_distance_travelled",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "correction_consumption",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.ship"
                    ),
                ),
            ],
            options={
                "db_table": "dcs_voyages",
            },
        ),
        migrations.CreateModel(
            name="DCSUploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(max_length=127)),
                ("s3_file_path", models.CharField(max_length=255)),
                ("deleted", models.BooleanField(default=False)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "dcs_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "DCS Type 1"), (2, "DCS Type 2")]
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.ship"
                    ),
                ),
            ],
            options={
                "db_table": "dcs_uploaded_files",
            },
        ),
    ]
