# Generated by Django 4.1.1 on 2023-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcsreporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcsuploadedfile",
            name="dcs_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "DCS Type 1"), (2, "DCS Type 2")], default=1
            ),
        ),
    ]
